title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
theme: jekyll-theme-minimal
---
---
@import "{{ site.theme }}";
body {
    font-family: "Benton Sans", "Helvetica Neue", helvetica, arial, sans-serif;
    margin: 2em;
    background-color: rgb(105,162,132);
background-color: linear-gradient(90deg, rgba(105,162,132,1) 29%, rgba(27,72,52,1) 61%);
font: helvetica 
}
